services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    environment:
      - QDRANT__SETTINGS__HTTP__PORT=6333
      - QDRANT__SETTINGS__GRPC__PORT=6334
      - QDRANT__SETTINGS__HOMEDIR=/qdrant/storage
      - QDRANT_USERNAME=admin
      - QDRANT_PASSWORD=zFKcYlkO0deJwVBc2fgyLXg1AHo51NBI 
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./database/qdrant_storage:/qdrant/storage
    restart: always

  injest-process:
    build: injestion/
    env_file:
      - path: ./injestion/env/localhost.env
        required: true
    depends_on:
      - qdrant